### PR TITLE
Add hotkey support (Resolves DanielGilbert/dgMicMute#2)

### PR DESCRIPTION
**Pull request by sco3tt**
This is a great tool for all of us who are constantly teleconferencing these days, and like one of the other commenters said, hotkey support would make it perfect.  I saw that you had already done some work to that end but it didn't look like anything had happened in the past few years so I went ahead and finished it.  I have never worked with WPF before so forgive some of my weird coding choices (e.g. how I dispatched all the events via the BootStrapper... if there's a cleaner way to do that, please don't hesitate to fix things up).

### CODE REVIEW

**Comment by DanielGilbert** [comment]
Thanks a lot for your contribution! Yes, I always wanted to finish up the hotkey feature, but never got it done. I also wanted to rewrite the tool, so that it can run under Windows, Linux, MacOS... Yeah, obviously that didn't happen.

I noticed a small glitch - when pressing the hotkey, the microphone icon won't get updated. I already found the line and will fix it once I merged the pull request. Then merge everything in testing, build a new version and setup, adapt readme and everything should be golden.

Again, thanks a lot for your effort! Happy hacking! :)

**Comment by sco3tt** [comment]
You're welcome!  And thank you for creating this project in the first place.  It's very well implemented and I'm sure you're seeing an uptick in downloads now that so many people are working from home and getting themselves into awkward situations with open mics during conference calls.

I originally had an idea to build a single-key HID keyboard (based on https://learn.adafruit.com/trinket-usb-keyboard/code) so I can have a big red "mic mute" toggle button on my desk, naively thinking that surely Windows supports a media keyboard code to mute the mic just like all the Speaker Volume Up/Down/Mute keycodes introduced in Windows 2000.  Fifteen minutes of googling proved me wrong, but it did lead me to your project which was 90% of what I needed, so thanks again for that.

I'm curious about the glitch you mentioned.  I haven't experienced that problem in any of my test configurations (compiled/tested with VS2019 on Windows 8.1 and Windows 10, VS2015 and VS2010 on Windows 7) so I'm interested to know what the defect is and how you resolved it.  Can you let me know when you check in your fix (or where to find it in the code if you already did and I overlooked it)?

**Comment by DanielGilbert** [comment]
> I originally had an idea to build a single-key HID keyboard (based on https://learn.adafruit.com/trinket-usb-keyboard/code) so I can have a big red "mic mute" toggle button on my desk, naively thinking that surely Windows supports a media keyboard code to mute the mic just like all the Speaker Volume Up/Down/Mute keycodes introduced in Windows 2000. 

Yeah, I was also surprised when I learned that Windows 7 (back in the days when I wrote this tool) doesn't have such functionality. With Windows 10, there is now a "Microphone" icon showing up, but it's also not made for muting. Nothing has changed in this regard. I really like your idea with the trinket. Add an RGB Cherry Switch to it, and it could get really fancy. :)

> Can you let me know when you check in your fix (or where to find it in the code if you already did and I overlooked it)?

Sure. [It's this line](https://github.com/DanielGilbert/dgMicMute/blob/ecd6f3b0117220b1463d5bc2f29e5fef8ce9434a/dgMicMute/NotifyIconViewModel.cs#L86). In your original PR, it read like this:

```csharp
public void HotkeyPressed(object sender, KeyPressedEventArgs e)
{
    _mic.Toggle();
}
```
Which is fine, and does what it's supposed to do. Unfortunately, it would'n propagate the change to the UI, which is why the notification icon didn't update (at least for me). I fixed it by implementing a short "Toggle"-function, which simply calls the "IsMuted"-Property, where all the necessary calls to the UI are made. If you click on the context menu, this is what you set. It's really just a checkbox being bound to the "IsMuted" property - so pressing the hotkey and clicking on the context menu entry are now basically equivalent in terms of workflow.

However, I should really refactor the code. I wouldn't write it like that nowadays - five (or better, six, since the original code is from 2014) years are a long time, and I learned some stuff along the way. :)

**Comment by sco3tt** [comment]
Ah, let me guess...  You have "Keep State" checked, correct?  I hadn't needed that option yet so never bothered testing my code with it enabled before, but I see now that it does exactly what you intended it to do.  It essentially treats my _mic.Toggle() call as though it originated from another app and overrides the change by reasserting "IsMuted = IsMuted" in the _mic_OnVolumeNotification event, leaving the icon (and for that matter, the mic state itself) unchanged.  Conversely when "Keep State" is left unchecked (as in all my testing) the _mic.Toggle() call results in IsMuted being set to the payload of that event, hence the reason why I was getting the expected icon updates and smugly thinking my code is bulletproof.

I've been coding long enough that you'd think I'd remember to test all the edge cases.  At least I learned something new today, so I still call that a win.  :)

**Pull request merged**
